

-- Throws PO Financial Dimensions into Joinable table (CostCenter and TradeValue) ---
Select *  INTO #VendorInvoiceTemp FROM (
SELECT        


                DAVC.TradeValue,DPT.Name,DAVC.COSTCENTERVALUE,VIJ.PURCHID, Row_Number() OVER(Partition by VIJ.PURCHID Order by VIJ.PURCHID) RowNumber


FROM            AxDB.dbo.VENDINVOICEJOUR VIJ 
			    INNER JOIN  AxDB.dbo.VENDTRANS VT 
				ON VIJ.LEDGERVOUCHER = VT.VOUCHER
				INNER JOIN AxDB.dbo.PURCHTABLE PT
				ON PT.PURCHID = VIJ.PURCHID
				LEFT JOIN AxDB.dbo.PURCHREQTABLE PRT
				ON PT.AVA_PURCHREQID = PRT.PURCHREQID
				INNER join AxDB.dbo.GENERALJOURNALENTRY GJE
				ON GJE.SUBLEDGERVOUCHER = VIJ.LEDGERVOUCHER
				INNER JOIN AxDB.dbo.GENERALJOURNALACCOUNTENTRY GJAE 
                ON GJE.RECID = GJAE.GENERALJOURNALENTRY
				INNER JOIN AxDB.dbo.DIMENSIONATTRIBUTEVALUECOMBINATION DAVC 
				ON DAVC.RECID = GJAE.LEDGERDIMENSION
				INNER JOIN AxDB.dbo.MAINACCOUNT MA 
				ON MA.RECID = DAVC.MAINACCOUNT
				INNER JOIN AxDB.dbo.DIMATTRIBUTEOMCOSTCENTER DACC 
				ON DACC.RECID = DAVC.COSTCENTER
				INNER JOIN AxDB.dbo.DIRPARTYTABLE DPT on DPT.RECID = DAVC.COSTCENTER

				
WHERE        (VT.LASTSETTLEDATE between '1/1/2018' and '2/28/2018') AND 
                         (VIJ.PURCHID LIKE N'MFAC%')

) a where a.rownumber = 1







SELECT        
                VIT.TradeValue as AXTrade,VIT.Name,VIT.CostCenterValue AS CostCenter,PRT.AVA_CRITICALPO,PRT.AVA_CRITICALPOREFERENCE,PRT.AVA_HEADERNOTES,prt.AVA_LOCATIONID,prt.AVA_ISSENTFROMCMS,PURCHNAME,
				PT.AVA_ISSENTFROMCMS,PT.ADDRESSREFRECID,PT.CREATEDDATETIME,PT.AVA_PURCHREQID,PT.REQATTENTION,
				PT.PURCHASETYPE,PT.AVA_WORKORDERNUMBER,VIJ.RECID, VIJ.PURCHID, VIJ.ORDERACCOUNT,
			    VIJ.INVOICEACCOUNT, VIJ.INVOICEID, VIJ.DOCUMENTDATE, VIJ.DUEDATE, 
                VIJ.PAYMENT, VIJ.INVOICEAMOUNT, VT.SETTLEAMOUNTCUR, VT.LASTSETTLEDATE, 
                VT.CLOSED, VT.LASTSETTLECOMPANY, VIJ.LEDGERVOUCHER, VIJ.DELIVERYNAME


FROM            AxDB.dbo.VENDINVOICEJOUR VIJ 
			    INNER JOIN  AxDB.dbo.VENDTRANS VT 
				ON VIJ.LEDGERVOUCHER = VT.VOUCHER
				INNER JOIN AxDB.dbo.PURCHTABLE PT
				ON PT.PURCHID = VIJ.PURCHID
				LEFT JOIN AxDB.dbo.PURCHREQTABLE PRT
				ON PT.AVA_PURCHREQID = PRT.PURCHREQID
				LEFT JOIN #VendorInvoiceTemp VIT
				ON VIT.PURCHID = VIJ.PURCHID
				


				
WHERE        (VT.LASTSETTLEDATE between '1/1/2018' and '2/28/2018') AND 
                         (VIJ.PURCHID LIKE N'MFAC%')

order by PURCHID

