

SELECT DISTINCT PURCHID, ITEMID
INTO #ITEMIDTEMP
FROM [AxDB].[dbo].[PURCHLINE]




Select MAM.*,IDST.*,ItemID.*,*

from 


(

Select
			    Coalesce(PT.AVA_PURCHREQID,PT2.AVA_PURCHREQID) PURCHREQID ,Coalesce(PT.AVA_WORKORDERNUMBER,PT2.AVA_WORKORDERNUMBER) WORKORDERNUMBER,
                Coalesce(PT.AVA_ISSENTFROMCMS,PT2.AVA_ISSENTFROMCMS) ISSENTFROMCMS,GJAE.TEXT,VIJ.INVOICEAMOUNT,COALESCE(VIJ.PURCHID,VPT.ORIGPURCHID) PURCHID,
                Coalesce(VIJ.INVOICEACCOUNT,PT2.ORDERACCOUNT) INVOICEACCOUNT,GJAE.REPORTINGCURRENCYAMOUNT,GJE.SUBLEDGERVOUCHER,GJE.JOURNALCATEGORY,GJE.LEDGER,GJAE.LEDGERACCOUNT,
				DAVC.TradeValue,DAVC.MAINACCOUNTVALUE,MA.NAME as 'Main Account Name',
				DAVC.COSTCENTER,DPT.Name,DAVC.COSTCENTERVALUE,GJAE.LEDGERDIMENSION,GJE.RECID,GJE.accountingdate



FROM            AxDB.dbo.GENERALJOURNALENTRY GJE 

                INNER JOIN AxDB.dbo.GENERALJOURNALACCOUNTENTRY GJAE 
                ON GJE.RECID = GJAE.GENERALJOURNALENTRY 
				INNER JOIN AxDB.dbo.DIMENSIONATTRIBUTEVALUECOMBINATION DAVC 
 				ON DAVC.RECID = GJAE.LEDGERDIMENSION
				INNER JOIN AxDB.dbo.MAINACCOUNT MA
				ON MA.RECID = DAVC.MAINACCOUNT
				INNER JOIN AxDB.dbo.DIMATTRIBUTEOMCOSTCENTER DACC 
				ON DACC.RECID = DAVC.COSTCENTER
				INNER JOIN AxDB.dbo.DIRPARTYTABLE DPT 
				ON DPT.RECID = DAVC.COSTCENTER
				LEFT JOIN AxDB.dbo.VENDINVOICEJOUR VIJ 
				ON VIJ.LEDGERVOUCHER = GJE.SUBLEDGERVOUCHER
				LEFT JOIN AxDB.dbo.VENDPACKINGSLIPTRANS VPT
				ON VPT.COSTLEDGERVOUCHER = GJE.SUBLEDGERVOUCHER
				LEFT JOIN AxDb.dbo.PURCHTABLE PT 
				ON PT.PURCHID = VIJ.PURCHID
				LEFT JOIN AxDb.dbo.PURCHTABLE PT2
				ON PT2.PURCHID = VPT.ORIGPURCHID
				

where GJE.AccountingDate between '1/1/2018' and '1/31/2018'

) a
left join #ITEMIDTEMP ItemID on a.PURCHID = ItemID.PURCHID
left join FM_OPERATIONS.dbo.Item_Description_Sector_Trade IDST on IDST.Item_Number = ItemID.ITEMID
LEFT JOIN FM_OPERATIONS.dbo.MainAccountMap MAM on MAM.[Main Account] = a.MAINACCOUNTVALUE
 